title: P3DOC
email: contact@goncalomb.com
description: >
  Unofficial documentation for the P3 educational CPU.

repository: goncalomb/p3doc

markdown: kramdown
theme:
gems:
exclude:
  - Gemfile
  - Gemfile.lock
