title: p3doc
email: contact@goncalomb.com
description: >
  Documentation for the P3 educational CPU.
baseurl: ""
url: ""

repository: goncalomb/p3doc

markdown: kramdown
theme:
gems:
exclude:
  - Gemfile
  - Gemfile.lock
